// SPDX-License-Identifier: GPL-3.0-only

/**
 * @file src/platform/linux/input/inputtino_seat.cpp
 * @brief Implementation for multi-seat input device isolation (udev-only).
 */
// standard includes
#include <cstdlib>
#include <exception>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <string>
#include <string_view>

// lib includes
#ifdef SUNSHINE_BUILD_WITH_UDEV
  #include <libudev.h>
#endif

// local includes
#include "inputtino_seat.h"
#include "src/config.h"
#include "src/logging.h"

using namespace std::literals;

namespace platf::inputtino_seat {

  namespace {
    constexpr auto RULE_FILENAME = "99-solarflare-seat.rules"sv;  ///< Transient udev rule file name.
    constexpr auto DEFAULT_RULES_DIR = "/run/udev/rules.d"sv;  ///< Default runtime udev rules directory.
    constexpr auto DEFAULT_SYSFS_ROOT = "/sys"sv;  ///< Default sysfs mount point.
    constexpr auto UEVENT_ACTION = "change\n"sv;  ///< uevent action written to sysfs.

    constexpr auto RULE_TEMPLATE = R"~(SUBSYSTEM=="input", KERNEL=="event*|js*", ATTRS{name}=="* (@SEAT@)", TAG+="seat", ENV{ID_SEAT}="@SEAT@"
)~"sv;  ///< Rule template with a @SEAT@ placeholder.

    /**
     * @brief Return the directory used for the transient udev rule.
     */
    std::string get_rules_dir() {
      if (const char *env = std::getenv("SOLARFLARE_TEST_UDEV_RULES_DIR")) {
        if (env[0] != '\0') {
          return env;
        }
      }
      return std::string(DEFAULT_RULES_DIR);
    }

    /**
     * @brief Return the root used for sysfs paths.
     */
    std::string get_sysfs_root() {
      if (const char *env = std::getenv("SOLARFLARE_TEST_SYSFS_ROOT")) {
        if (env[0] != '\0') {
          return env;
        }
      }
      return std::string(DEFAULT_SYSFS_ROOT);
    }

    /**
     * @brief Check whether a seat name enables isolation.
     */
    bool seat_valid(std::string_view seat) {
      return !seat.empty() && seat != "seat0"sv;
    }

    /**
     * @brief Check whether the seat name can be safely embedded in a udev rule.
     */
    bool seat_safe_for_rule(std::string_view seat) {
      return seat.find('"') == std::string_view::npos &&
             seat.find('\\') == std::string_view::npos &&
             seat.find('\n') == std::string_view::npos;
    }

    /**
     * @brief Build the content of the transient udev rule.
     */
    std::string build_rule_content(std::string_view seat) {
      std::string content;
      content.reserve(128 + seat.size() * 2);
      content += "# Auto-generated by SolarFlare for input seat isolation\n";

      std::string_view tmpl = RULE_TEMPLATE;
      std::size_t pos = 0;
      while (pos < tmpl.size()) {
        auto placeholder = tmpl.find("@SEAT@", pos);
        if (placeholder == std::string_view::npos) {
          content += tmpl.substr(pos);
          break;
        }
        content += tmpl.substr(pos, placeholder - pos);
        content += seat;
        pos = placeholder + 6;
      }
      return content;
    }

    /**
     * @brief Read the entire content of a text file.
     * @return The file content, or an empty string if the file cannot be read.
     */
    std::string read_text_file(const std::filesystem::path &path) {
      std::ifstream ifs(path);
      if (!ifs) {
        return {};
      }
      std::string content((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());
      return content;
    }

    /**
     * @brief Write the transient udev rule for the given seat.
     * @return True if the rule was written successfully.
     */
    bool write_rule(const std::filesystem::path &path, std::string_view seat) {
      std::ofstream ofs(path, std::ios::trunc);
      if (!ofs) {
        return false;
      }
      ofs << build_rule_content(seat);
      return ofs.good();
    }

    /**
     * @brief Run a udevadm sub-command, logging a warning on failure.
     */
    bool run_udevadm(const char *args) {
      std::string cmd = "udevadm ";
      cmd += args;
      cmd += " 2>/dev/null";

      const int rc = std::system(cmd.c_str());
      if (rc != 0) {
        BOOST_LOG(warning) << "inputtino_seat: 'udevadm " << args << "' returned " << rc << ""sv;
        return false;
      }
      return true;
    }

    /**
     * @brief Write the @c change action to a sysfs @c uevent file.
     * @return True if the write succeeded.
     */
    bool write_uevent(const std::filesystem::path &path) {
      std::ofstream ofs(path);
      if (!ofs) {
        return false;
      }
      ofs << UEVENT_ACTION;
      return ofs.good();
    }

#ifdef SUNSHINE_BUILD_WITH_UDEV
    /**
     * @brief Resolve a /dev/input node to its sysfs syspath.
     */
    std::string resolve_syspath_for_node(struct udev *udev, std::string_view node) {
      const std::string filename = std::filesystem::path(node).filename().string();
      struct udev_device *device = udev_device_new_from_subsystem_sysname(udev, "input", filename.c_str());
      if (!device) {
        return {};
      }

      const char *syspath = udev_device_get_syspath(device);
      const char *devnode = udev_device_get_devnode(device);
      std::string result;
      if (syspath && devnode && node == devnode) {
        result = syspath;
      }
      udev_device_unref(device);
      return result;
    }

    /**
     * @brief Map an absolute sysfs syspath to the test-configurable root.
     */
    std::filesystem::path map_sysfs_uevent_path(std::string_view syspath) {
      const std::string root = get_sysfs_root();
      if (!syspath.starts_with("/sys"sv)) {
        return std::filesystem::path(root) / syspath;
      }

      std::string_view rest = syspath.substr(4);
      std::filesystem::path path(root);
      if (!rest.empty() && rest.front() == '/') {
        rest.remove_prefix(1);
      }
      return path / std::string(rest);
    }
#endif
  }  // namespace

  std::string get_target_seat() {
    // Config override takes precedence
    if (!config::input.input_seat.empty()) {
      return config::input.input_seat;
    }

    // Fall back to XDG_SEAT environment variable
    if (const char *seat = std::getenv("XDG_SEAT")) {
      if (seat[0] != '\0') {
        return seat;
      }
    }

    return {};
  }

  bool seat_isolation_active() {
    const auto seat = get_target_seat();
    return !seat.empty() && seat != "seat0"sv;
  }

  bool assign_device_to_seat(std::string_view device_name, const std::vector<std::string> &device_nodes, std::string_view seat) {
    if (!seat_valid(seat)) {
      return false;
    }

    if (!seat_safe_for_rule(seat)) {
      BOOST_LOG(warning) << "inputtino_seat: refusing seat name containing rule metacharacters"sv;
      return false;
    }

#ifndef SUNSHINE_BUILD_WITH_UDEV
    BOOST_LOG(warning) << "inputtino_seat: built without libudev support; seat routing is best-effort"sv;
#endif

    BOOST_LOG(info) << "inputtino_seat: assigning device '" << device_name << "' to seat '" << seat << "'"sv;

    // Write the transient udev rule if it is missing or stale. The reload+settle
    // below is gated on `rule_written` so a cache hit (the on-disk rule already
    // matched the desired content) does NOT re-run udevadm on every call.
    bool rule_written = false;
    try {
      namespace fs = std::filesystem;
      const auto rules_dir = fs::path(get_rules_dir());
      const auto rules_file = rules_dir / std::string(RULE_FILENAME);

      if (!fs::create_directories(rules_dir) && !fs::exists(rules_dir)) {
        BOOST_LOG(warning) << "inputtino_seat: cannot create rules directory " << rules_dir << "; continuing without transient rule"sv;
      }

      const auto desired_content = build_rule_content(seat);
      const auto existing_content = read_text_file(rules_file);
      if (existing_content != desired_content) {
        if (!write_rule(rules_file, seat)) {
          BOOST_LOG(warning) << "inputtino_seat: failed to write udev rule to " << rules_file << "; continuing"sv;
        } else {
          rule_written = true;
          BOOST_LOG(info) << "inputtino_seat: wrote transient udev rule " << rules_file << ""sv;
        }
      }

      if (rule_written) {
        run_udevadm("control --reload-rules");
        run_udevadm("settle");
      }
    } catch (const std::exception &e) {
      BOOST_LOG(warning) << "inputtino_seat: exception while writing transient udev rule: " << e.what() << ""sv;
    }

    // Synthesize a change uevent for each supplied device node.
    bool any_uevent = false;
#ifdef SUNSHINE_BUILD_WITH_UDEV
    struct udev *udev = udev_new();
    if (!udev) {
      BOOST_LOG(warning) << "inputtino_seat: failed to create udev context; falling back to udevadm triggers"sv;
    }
#else
    void *udev = nullptr;
#endif

    for (const auto &node : device_nodes) {
      bool written = false;
#ifdef SUNSHINE_BUILD_WITH_UDEV
      if (udev) {
        const auto syspath = resolve_syspath_for_node(udev, node);
        if (!syspath.empty()) {
          const auto uevent_path = map_sysfs_uevent_path(syspath) / "uevent";
          if (write_uevent(uevent_path)) {
            written = true;
            any_uevent = true;
            BOOST_LOG(info) << "inputtino_seat: wrote change uevent to " << uevent_path << ""sv;
          }
        }
      }
#endif
      if (!written) {
        std::string trigger = "trigger --name-match=";
        trigger += node;
        trigger += " --action=change";
        if (run_udevadm(trigger.c_str())) {
          any_uevent = true;
        }
      }
    }

#ifdef SUNSHINE_BUILD_WITH_UDEV
    if (udev) {
      udev_unref(udev);
    }
#endif

    if (!any_uevent) {
      // Last resort: a subsystem-wide change trigger.
      run_udevadm("trigger --subsystem-match=input --action=change");
    }

    return true;
  }

}  // namespace platf::inputtino_seat
